apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-pro-api-ingress
  namespace: gym-pro
  labels:
    app: gym-pro-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: api.gympro.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gym-pro-api-svc
                port:
                  number: 80
