apiVersion: v1
kind: Secret
metadata:
  name: gym-pro-api-secret
  namespace: gym-pro
type: Opaque
stringData:
  POSTGRES_USER: gymadmin
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: gym_pro_db
  DB_USER: gymadmin
  DB_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME_LONG_RANDOM_STRING
  REDIS_PASSWORD: ""
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SENDGRID_API_KEY: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  FACEBOOK_APP_ID: ""
  FACEBOOK_APP_SECRET: ""
  CLOUDINARY_URL: ""
  GEMINI_API_KEY: ""
  EXPO_ACCESS_TOKEN: ""
